Contributor:
  access:
    site:
      login: true
      review: true
      submit: true
  readableName: Contributor
  description: 'Contributors can review, submit, and report cafes.'
  icon: edit
  enabled: true
