title: NomadBeans
default_lang: en
author:
  name: 'James Auble'
  email: james.auble@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'NomadBeans is a cafe finder for Digital Nomads.'
  robots: noindex
summary:
  enabled: true
  format: short
  size: 200
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
twitter_url: null
instagram_url: null
youtube_url: null
facebook_url: null
tiktok_url: null
linkedin_url: null
