title: About
"@extends":
  type: default
  context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          fields:
            header.featured_image_alt_description:
              type: text
              label: Featured Image Alt Description
